//! Echo — Nova's native client, as a library.
//!
//! Everything a client does that is not platform-specific lives here: the
//! connection sequence, the control channel, depacketisation, FEC repair,
//! decryption, and the keyframe gate. The headless CLI ([`crate`]'s binary) and
//! the Android bridge (`echo-android`) are both thin shells over this — which is
//! the point. A desktop `echo-client stream` therefore exercises the same code
//! an Android session will, and that is the only validation available for a
//! stack that has not met real hardware yet.
//!
//! What is *not* here: video decoding, UI, sockets belonging to a platform, and
//! anything Windows. Protocol and identity live one level down in `nova-core`,
//! shared with the host.
//!
//! ## Identity — a correction worth stating plainly
//!
//! Echo does **not** read `nova_paired.json`. That file is the *host's* trust
//! store: it maps a client certificate fingerprint to a device record, and it
//! contains other devices' public certificates and no private keys at all.
//! Reading it would give Echo nothing it could authenticate with.
//!
//! Instead Echo has its own identity, generated on first run and persisted
//! (`echo.cert.der` / `echo.key.der`), exactly as a Moonlight client does. The
//! host learns to trust it through the ordinary pairing flow — that is what puts
//! Echo's fingerprint into `nova_paired.json`. Until that pairing happens, Echo
//! can talk to the relay (which accepts any certificate) but Nova will refuse
//! it, which is the trust model working as intended.
//!
//! On Android the identity lives in app-private storage and is generated by the
//! same [`nova_core::identity::Identity::load_or_create`] call. There is still
//! no client-side implementation of the pairing handshake itself, on any
//! platform — see `HANDOFF_ECHO_ANDROID.md` §5.
//!
//! ## Layout
//!
//! - [`session`] — the connection sequence and its [`session::Progress`] events.
//! - [`control`] — mutual TLS to the host, over the punched path or a LAN
//!   socket.
//! - [`receiver`] — the one socket reader, reassembly, FEC, and decryption.
//! - [`gate`] — the keyframe gate that stands between the stream and a decoder.

pub mod control;
pub mod gate;
pub mod input;
pub mod mic;
pub mod pairing;
pub mod receiver;
pub mod session;
