//! Media encryption for Echo sessions — AES-128-GCM over whole encoded frames.
//!
//! GameStream sends video in the clear (Nova's DESCRIBE advertises
//! `encryptionSupported:0`, and Sunshine behaves the same way), which is
//! defensible on a LAN and indefensible the moment a session crosses the
//! internet through a punched UDP path. Echo therefore encrypts its own media,
//! and this module is the single implementation both peers use — the same rule
//! that put [`crate::punch`] here rather than in either binary.
//!
//! ## What is encrypted, and where in the pipeline
//!
//! The unit is a **complete encoded frame**, sealed *before* it is sharded into
//! datagrams — never the individual datagram. That ordering is forced by
//! Reed-Solomon FEC: parity is computed across the shards that are actually
//! transmitted, so encrypting after sharding would work, but encrypting each
//! shard separately would add 16 bytes of tag to every packet (about 1.5% of a
//! 1024-byte payload, multiplied across every shard including parity) and give
//! an attacker a per-packet oracle. Sealing the frame first means:
//!
//! - one 16-byte tag per frame rather than per packet,
//! - FEC still recovers lost shards, because it operates on ciphertext bytes
//!   like any other bytes,
//! - and the receiver authenticates the frame **after** reassembly, so a forged
//!   or corrupted shard that FEC could not repair fails the tag check instead of
//!   reaching the decoder.
//!
//! ## Nonce construction
//!
//! A repeated (key, nonce) pair is catastrophic for GCM — it leaks the XOR of
//! two plaintexts and, worse, the authentication subkey. The nonce here is
//! therefore constructed, never random:
//!
//! ```text
//!   [ salt (4B) | stream id (4B, BE) | counter (4B, BE) ]
//! ```
//!
//! The salt is fresh per session, the stream id separates video from audio from
//! anything added later, and the counter is that stream's monotonic index —
//! for video, exactly the wire frame index `rtp.rs` already maintains. Since a
//! session's key is generated fresh and never reused, and no stream ever emits
//! the same index twice within a session, collisions cannot occur without a
//! programming error that the [`nonce_uniqueness`](tests) test is there to
//! catch.
//!
//! Note the consequence: **the receiver must know the frame index before it can
//! decrypt**, which it does — the index is in the NV_VIDEO_PACKET header of
//! every shard, in the clear. That is deliberate. Encrypting the index would
//! make loss recovery undecryptable, and it reveals nothing an observer could
//! not infer from counting packets.
//!
//! ## What the tag covers
//!
//! Associated data binds each frame to its position and type, so a frame cannot
//! be silently replayed at a different index or relabelled from P-frame to IDR
//! (which would let an attacker stall a decoder by feeding it a "keyframe" that
//! is not one). The AAD is not transmitted — both sides derive it from headers
//! they already have.

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes128Gcm, Nonce};

/// Bytes added to a frame by sealing it: the GCM authentication tag.
pub const CRYPTO_OVERHEAD: usize = 16;

/// Stream discriminator for video frames.
pub const STREAM_VIDEO: u32 = 1;
/// Stream discriminator for audio frames.
pub const STREAM_AUDIO: u32 = 2;

/// Per-session media key material.
///
/// Generated by the host when a session starts and handed to the client over
/// the Echo RPC — which is mutual TLS, so the key never crosses the network in
/// the clear and is bound to a certificate the host has already paired. There
/// is deliberately no key exchange of our own here: inventing one when a
/// mutually-authenticated TLS channel is already open would be adding a second,
/// weaker path to the same secret.
///
/// `Debug` prints only the salt. A key that lands in a log file is a key that
/// is no longer secret, and this struct passes through code that logs freely.
#[derive(Clone, PartialEq, Eq)]
pub struct SessionKeys {
    key: [u8; 16],
    salt: [u8; 4],
}

impl std::fmt::Debug for SessionKeys {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SessionKeys")
            .field("key", &"<redacted>")
            .field("salt", &hex::encode(self.salt))
            .finish()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CryptoError {
    /// The tag did not verify: the frame was corrupted, forged, or arrived
    /// labelled with an index or type other than the one it was sealed under.
    Authentication,
    /// Fewer bytes than a bare tag — cannot be a sealed frame.
    Truncated,
    /// Key material was not the expected length or encoding.
    BadKeyMaterial(String),
}

impl std::fmt::Display for CryptoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Authentication => write!(
                f,
                "frame failed authentication — corrupted, forged, or replayed at the wrong index"
            ),
            Self::Truncated => write!(f, "sealed frame is shorter than the authentication tag"),
            Self::BadKeyMaterial(why) => write!(f, "bad key material: {why}"),
        }
    }
}

impl std::error::Error for CryptoError {}

impl SessionKeys {
    /// Fresh random key and salt from the OS CSPRNG.
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut key = [0u8; 16];
        let mut salt = [0u8; 4];
        // `OsRng` reads the operating system's entropy source directly rather
        // than a seeded userspace PRNG — the only acceptable source for a key
        // that protects a live session.
        rand::rngs::OsRng.fill_bytes(&mut key);
        rand::rngs::OsRng.fill_bytes(&mut salt);
        Self { key, salt }
    }

    /// Hex encoding for transport over the (TLS-protected) control channel.
    /// 40 hex chars: 16-byte key followed by the 4-byte salt.
    pub fn to_hex(&self) -> String {
        let mut raw = Vec::with_capacity(20);
        raw.extend_from_slice(&self.key);
        raw.extend_from_slice(&self.salt);
        hex::encode(raw)
    }

    pub fn from_hex(text: &str) -> Result<Self, CryptoError> {
        let raw = hex::decode(text.trim())
            .map_err(|e| CryptoError::BadKeyMaterial(e.to_string()))?;
        if raw.len() != 20 {
            return Err(CryptoError::BadKeyMaterial(format!(
                "expected 20 bytes (16 key + 4 salt), got {}",
                raw.len()
            )));
        }
        let mut key = [0u8; 16];
        let mut salt = [0u8; 4];
        key.copy_from_slice(&raw[..16]);
        salt.copy_from_slice(&raw[16..]);
        Ok(Self { key, salt })
    }

    fn cipher(&self) -> Aes128Gcm {
        // Infallible for a 16-byte key, which the type guarantees.
        Aes128Gcm::new_from_slice(&self.key).expect("16-byte AES-128 key")
    }

    fn nonce(&self, stream: u32, counter: u32) -> [u8; 12] {
        let mut n = [0u8; 12];
        n[0..4].copy_from_slice(&self.salt);
        n[4..8].copy_from_slice(&stream.to_be_bytes());
        n[8..12].copy_from_slice(&counter.to_be_bytes());
        n
    }

    /// Seal one complete encoded frame. Output is `ciphertext || tag`, exactly
    /// [`CRYPTO_OVERHEAD`] bytes longer than the input.
    pub fn seal(&self, stream: u32, counter: u32, frame_type: u8, plaintext: &[u8]) -> Vec<u8> {
        let nonce = self.nonce(stream, counter);
        let aad = associated_data(stream, counter, frame_type);
        self.cipher()
            .encrypt(
                Nonce::from_slice(&nonce),
                Payload { msg: plaintext, aad: &aad },
            )
            // AES-GCM encryption fails only on absurd input lengths (2^36 bytes
            // and beyond); a video frame cannot reach that.
            .expect("AES-GCM seal cannot fail for frame-sized input")
    }

    /// Open a frame sealed with [`seal`](Self::seal) under the same stream,
    /// counter, and frame type. Any mismatch fails the tag check rather than
    /// returning wrong plaintext.
    pub fn open(
        &self,
        stream: u32,
        counter: u32,
        frame_type: u8,
        sealed: &[u8],
    ) -> Result<Vec<u8>, CryptoError> {
        if sealed.len() < CRYPTO_OVERHEAD {
            return Err(CryptoError::Truncated);
        }
        let nonce = self.nonce(stream, counter);
        let aad = associated_data(stream, counter, frame_type);
        self.cipher()
            .decrypt(
                Nonce::from_slice(&nonce),
                Payload { msg: sealed, aad: &aad },
            )
            .map_err(|_| CryptoError::Authentication)
    }
}

/// Associated data: what the tag commits to beyond the payload itself. Never
/// transmitted — both peers reconstruct it from headers they already hold.
fn associated_data(stream: u32, counter: u32, frame_type: u8) -> [u8; 9] {
    let mut aad = [0u8; 9];
    aad[0..4].copy_from_slice(&stream.to_be_bytes());
    aad[4..8].copy_from_slice(&counter.to_be_bytes());
    aad[8] = frame_type;
    aad
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_sealed_frame_opens_to_the_original() {
        let keys = SessionKeys::generate();
        let frame = b"\x00\x00\x00\x01\x67 pretend SPS and slice data".repeat(40);

        let sealed = keys.seal(STREAM_VIDEO, 1, 2, &frame);
        assert_eq!(sealed.len(), frame.len() + CRYPTO_OVERHEAD);
        assert_ne!(&sealed[..frame.len()], &frame[..], "payload must not be plaintext");

        let opened = keys.open(STREAM_VIDEO, 1, 2, &sealed).expect("opens");
        assert_eq!(opened, frame);
    }

    /// The point of the AAD. A frame lifted from the stream and re-injected at
    /// a different index — or relabelled as a keyframe to stall a decoder —
    /// must fail, not decode.
    #[test]
    fn a_frame_replayed_at_the_wrong_index_or_type_is_refused() {
        let keys = SessionKeys::generate();
        let sealed = keys.seal(STREAM_VIDEO, 7, 1, b"frame seven");

        assert_eq!(keys.open(STREAM_VIDEO, 7, 1, &sealed).unwrap(), b"frame seven");
        assert_eq!(keys.open(STREAM_VIDEO, 8, 1, &sealed), Err(CryptoError::Authentication));
        assert_eq!(keys.open(STREAM_VIDEO, 7, 2, &sealed), Err(CryptoError::Authentication));
        assert_eq!(keys.open(STREAM_AUDIO, 7, 1, &sealed), Err(CryptoError::Authentication));
    }

    /// FEC repairs some losses; a shard it could not repair leaves a corrupt
    /// frame, and the tag is what stops that reaching the decoder.
    #[test]
    fn a_corrupted_frame_fails_authentication() {
        let keys = SessionKeys::generate();
        let mut sealed = keys.seal(STREAM_VIDEO, 3, 1, &b"x".repeat(500));
        sealed[100] ^= 0x01;
        assert_eq!(keys.open(STREAM_VIDEO, 3, 1, &sealed), Err(CryptoError::Authentication));
    }

    #[test]
    fn another_sessions_key_cannot_open_this_sessions_frames() {
        let a = SessionKeys::generate();
        let b = SessionKeys::generate();
        let sealed = a.seal(STREAM_VIDEO, 1, 2, b"secret desktop");
        assert_eq!(b.open(STREAM_VIDEO, 1, 2, &sealed), Err(CryptoError::Authentication));
    }

    /// The nonce must be unique for every (stream, counter) a session can
    /// produce. This is the invariant whose violation breaks GCM outright, so
    /// it is asserted directly rather than trusted to review.
    #[test]
    fn nonce_uniqueness() {
        let keys = SessionKeys::generate();
        let mut seen = std::collections::HashSet::new();
        for stream in [STREAM_VIDEO, STREAM_AUDIO] {
            for counter in 0..5000u32 {
                assert!(
                    seen.insert(keys.nonce(stream, counter)),
                    "nonce reuse at stream {stream} counter {counter}"
                );
            }
        }
    }

    #[test]
    fn keys_survive_the_hex_round_trip_used_by_the_rpc() {
        let keys = SessionKeys::generate();
        let text = keys.to_hex();
        assert_eq!(text.len(), 40);
        let restored = SessionKeys::from_hex(&text).expect("round trip");
        assert_eq!(restored, keys);

        // The client's half of the handshake is fallible input.
        assert!(SessionKeys::from_hex("not hex").is_err());
        assert!(SessionKeys::from_hex("aabb").is_err());
    }

    /// A key must never be printable by accident: this struct passes through
    /// code that logs its state freely.
    #[test]
    fn debug_never_reveals_the_key() {
        let keys = SessionKeys::generate();
        let rendered = format!("{keys:?}");
        assert!(rendered.contains("redacted"));
        assert!(!rendered.contains(&hex::encode(keys.key)));
    }

    #[test]
    fn truncated_input_is_reported_as_such() {
        let keys = SessionKeys::generate();
        assert_eq!(keys.open(STREAM_VIDEO, 1, 1, b"short"), Err(CryptoError::Truncated));
    }
}
